SplineFontDB: 3.2
FontName: TeXGyreScholaMath-FlashTweaks
FullName: TeXGyreScholaMath-FlashTweaks
FamilyName: TeX Gyre Schola MFlashTweaks
Weight: Regular
Copyright: Copyright 2014 for Tex Gyre Schola Math OTF by B. Jackowski, P. Strzelczyk and P. Pianowski (on behalf of TeX users groups). This work is released under the GUST Font License -- see http://tug.org/fonts/licenses/GUST-FONT-LICENSE.txt for details.
Version: Version 1.533
ItalicAngle: 0
UnderlinePosition: -240
UnderlineWidth: 40
Ascent: 796
Descent: 204
InvalidEm: 0
sfntRevision: 0x00018872
LayerCount: 2
Layer: 0 0 "Back" 1
Layer: 1 0 "Fore" 0
XUID: [1021 408 74888886 15448]
StyleMap: 0x0040
FSType: 12
OS2Version: 4
OS2_WeightWidthSlopeOnly: 0
OS2_UseTypoMetrics: 1
CreationTime: 1409920079
ModificationTime: 1780461260
PfmFamily: 17
TTFWeight: 400
TTFWidth: 5
LineGap: 200
VLineGap: 0
Panose: 2 0 5 3 0 0 0 0 0 0
OS2TypoAscent: 796
OS2TypoAOffset: 0
OS2TypoDescent: -204
OS2TypoDOffset: 0
OS2TypoLinegap: 200
OS2WinAscent: 2539
OS2WinAOffset: 0
OS2WinDescent: 2019
OS2WinDOffset: 0
HheadAscent: 796
HheadAOffset: 0
HheadDescent: -204
HheadDOffset: 0
OS2SubXSize: 650
OS2SubYSize: 699
OS2SubXOff: 0
OS2SubYOff: 140
OS2SupXSize: 650
OS2SupYSize: 699
OS2SupXOff: 0
OS2SupYOff: 479
OS2StrikeYSize: 49
OS2StrikeYPos: 258
OS2CapHeight: 722
OS2XHeight: 466
OS2Vendor: 'PfEd'
OS2CodePages: 60000193.0dd40000
OS2UnicodeRanges: a10000ef.4201f9ee.02000000.00000000
Lookup: 3 0 0 "'aalt' Access All Alternates in Mathematical text layout lookup 0" { "'aalt' Access All Alternates in Mathematical text layout lookup 0 subtable"  } ['aalt' ('math' <'dflt' > ) ]
Lookup: 1 0 0 "'dtls' Dotless Forms in Mathematical text layout lookup 1" { "'dtls' Dotless Forms in Mathematical text layout lookup 1 subtable"  } ['dtls' ('math' <'dflt' > ) ]
Lookup: 3 0 0 "'ssty' Math Script Style in Mathematical text layout lookup 2" { "'ssty' Math Script Style in Mathematical text layout lookup 2 subtable"  } ['ssty' ('math' <'dflt' > ) ]
MarkAttachClasses: 1
DEI: 91125
LangName: 1033 "" "" "" "FontForge 2.0 : TeXGyreScholaMath-FlashTweaks : 2-6-2026" "" "Version 1.533" "" "Please refer to the Copyright section for the font trademark attribution notices." "" "" "" "" "" "" "" "" "TeX Gyre Schola Math" "Regular"
MATH:ScriptPercentScaleDown: 77
MATH:ScriptScriptPercentScaleDown: 60
MATH:DelimitedSubFormulaMinHeight: 1333
MATH:DisplayOperatorMinHeight: 1800
MATH:MathLeading: 130 
MATH:AxisHeight: 260 
MATH:AccentBaseHeight: 486 
MATH:FlattenedAccentBaseHeight: 702 
MATH:SubscriptShiftDown: 239 
MATH:SubscriptTopMax: 312 
MATH:SubscriptBaselineDropMin: 120 
MATH:SuperscriptShiftUp: 346 
MATH:SuperscriptShiftUpCramped: 287 
MATH:SuperscriptBottomMin: 208 
MATH:SuperscriptBaselineDropMax: 239 
MATH:SubSuperscriptGapMin: 130 
MATH:SuperscriptBottomMaxWithSubscript: 325 
MATH:SpaceAfterScript: 40 
MATH:UpperLimitGapMin: 100 
MATH:UpperLimitBaselineRiseMin: 100 
MATH:LowerLimitGapMin: 100 
MATH:LowerLimitBaselineDropMin: 459 
MATH:StackTopShiftUp: 395 
MATH:StackTopDisplayStyleShiftUp: 629 
MATH:StackBottomShiftDown: 234 
MATH:StackBottomDisplayStyleShiftDown: 642 
MATH:StackGapMin: 100 
MATH:StackDisplayStyleGapMin: 130 
MATH:StretchStackTopShiftUp: 100 
MATH:StretchStackBottomShiftDown: 459 
MATH:StretchStackGapAboveMin: 100 
MATH:StretchStackGapBelowMin: 100 
MATH:FractionNumeratorShiftUp: 395 
MATH:FractionNumeratorDisplayStyleShiftUp: 629 
MATH:FractionDenominatorShiftDown: 234 
MATH:FractionDenominatorDisplayStyleShiftDown: 642 
MATH:FractionNumeratorGapMin: 100 
MATH:FractionNumeratorDisplayStyleGapMin: 130 
MATH:FractionRuleThickness: 70 
MATH:FractionDenominatorGapMin: 100 
MATH:FractionDenominatorDisplayStyleGapMin: 130 
MATH:SkewedFractionHorizontalGap: 300 
MATH:SkewedFractionVerticalGap: 66 
MATH:OverbarVerticalGap: 100 
MATH:OverbarRuleThickness: 70 
MATH:OverbarExtraAscender: 50 
MATH:UnderbarVerticalGap: 100 
MATH:UnderbarRuleThickness: 70 
MATH:UnderbarExtraDescender: 50 
MATH:RadicalVerticalGap: 100 
MATH:RadicalDisplayStyleVerticalGap: 100 
MATH:RadicalRuleThickness: 70 
MATH:RadicalExtraAscender: 100 
MATH:RadicalKernBeforeDegree: 40 
MATH:RadicalKernAfterDegree: -428 
MATH:RadicalDegreeBottomRaisePercent: 55
MATH:MinConnectorOverlap: 35
Encoding: UnicodeFull
UnicodeInterp: none
NameList: ΤεΧ Names
DisplaySize: -48
AntiAlias: 1
FitToEm: 0
WinInfo: 38 38 14
BeginPrivate: 9
BlueValues 31 [-15 0 466 481 704 704 722 737]
OtherBlues 11 [-316 -202]
BlueScale 7 0.04546
BlueShift 1 6
BlueFuzz 1 0
StdHW 4 [70]
StdVW 4 [70]
StemSnapH 26 [31 36 43 47 54 58 70 112]
StemSnapV 35 [42 46 70 78 90 94 103 108 112 124]
EndPrivate
EndSplineFont
